apiVersion: v1
entries:
  christian-service:
  - apiVersion: v2
    created: "2025-08-18T15:35:18.089915+10:00"
    description: A Helm chart for christian Services
    digest: f148e6d6642ad7e0905a4d5eb38e0f1fcf1e21e26b5f4fe9f189d01c89481689
    icon: https://avatars.githubusercontent.com/u/25603064?s=200&v=4
    name: christian-service
    type: application
    urls:
    - christian-service-1.0.0.tgz
    version: 1.0.0
generated: "2025-08-18T15:35:18.089484+10:00"
