{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ .Values.global.serviceName }}-service-provider-class
  namespace:  {{ include "christian-service.namespace" . }}
  labels:
    {{- include "christian-service.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    preferredAddressType: {{ .Values.secretProviderClass.parameters.preferredAddressType | quote }}
    region: {{ .Values.global.awsRegion }}
    usePodIdentity: {{ .Values.secretProviderClass.parameters.userPodIdentity | quote }}
    objects: |
{{- range .Values.secretProviderClass.parameters.objects }}
      - objectName: {{ .objectName | quote }}
        objectType: {{ .objectType | quote }}
{{- if .jmesPath }}
        jmesPath:
{{- range .jmesPath }}
          - path: {{ .path }}
            objectAlias: {{ .objectAlias }}
{{- end }}
{{- end }}
{{- end }}    
{{- end }}
