{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- $serviceName := .Values.global.serviceName }}
  {{- if .Values.serviceAccount.name }}
  {{- $serviceName = .Values.serviceAccount.name }}
  {{- end }}
  name: {{ $serviceName }}-service-account
  namespace:  {{ include "christian-service.namespace" . }}
  labels:
    {{- include "christian-service.labels" . | nindent 4 }}
  annotations:
    {{- $roleName := .Values.global.serviceName }}
    {{- if .Values.serviceAccount.iamRoleName }}
    {{- $roleName = .Values.serviceAccount.iamRoleName }}
    {{- end }}
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.awsAccountId }}:role/{{ $roleName }}-service-account

{{- end}}
